# Generated by Django 5.2.11 on 2026-04-23 21:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_share_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Member monthly capital share target', max_digits=12),
        ),
    ]
