# Generated by Django 5.2.11 on 2026-04-09 10:38

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Next_of_kin_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[Users.models.validate_kenyan_phone]),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
