# Generated by Django 5.2.11 on 2026-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
