# Generated by Django 5.2.11 on 2026-04-07 19:24

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pf_number',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[Users.models.validate_pf_number]),
        ),
    ]
