# Generated by Django 5.2.11 on 2026-03-19 18:41

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[Users.models.validate_kenyan_phone]),
        ),
    ]
