# Generated by Django 5.2.11 on 2026-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_gross_salary_profile_net_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Staff'), ('3', 'Treasurer'), ('4', 'Member'), ('5', 'Human Resource')], default='4', max_length=10),
        ),
    ]
