# Generated by Django 5.2.11 on 2026-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_monthly_share_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='monthly_share_target',
        ),
        migrations.AddField(
            model_name='profile',
            name='share_goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
