# Generated by Django 5.2.11 on 2026-04-12 06:50

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pf_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[Users.models.validate_pf_number]),
        ),
    ]
