# Generated by Django 5.2.11 on 2026-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_profile_monthly_share_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreed_to_declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='declaration_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
