# Generated by Django 5.2.11 on 2026-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_profile_agreed_to_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract_expiry',
            field=models.DateField(blank=True, help_text='Required only for contract-based members', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('PERMANENT', 'Permanent & Pensionable'), ('CONTRACT', 'Contract Terms')], default='PERMANENT', max_length=20),
        ),
    ]
