# Generated by Django 5.2.11 on 2026-04-13 10:04

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_profile_pf_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[Users.models.validate_kenyan_phone]),
        ),
    ]
