# Generated by Django 5.2.11 on 2026-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary_needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
