# Generated by Django 5.2.11 on 2026-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_profile_salary_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
