# Generated by Django 5.2.11 on 2026-04-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_profile_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
