# Generated by Django 5.2.11 on 2026-04-17 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_profile_membership_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
