# Generated by Django 5.2.11 on 2026-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_profile_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_saving_target',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
