from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('', views.home, name="home"),
    path ('about', views.about, name= "about"),
    path ('Contact', views.Contact, name= "Contact"),
    path ('Service', views.Service, name= "Service"),
    path('member_dashboard',views.member_dashboard,name='member_dashboard'),
    path('deposit_savings',views.deposit_savings, name='deposit_savings'),
    path('apply_loan',views.apply_loan, name='apply_loan'),
    path('purchase_shares',views.purchase_shares, name='purchase_shares'),
    path ('Setting_loan',views.Setting_loan,name='Setting_loan'),
    path('admin_dashboard',views.admin_dashboard,name='admin_dashboard'),
    path ('LoanP',views.LoanP,name='LoanP'),
    path ('pay_loan',views.pay_loan, name='pay_loan'),
    path ('staff_dashboard',views.staff_dashboard, name='staff_dashboard'),
    # path('initiate_stk_push_shares',views.initiate_stk_push_shares, name='initiate_stk_push_shares'),
path('treasury/buy-shares/<int:member_id>/', views.treasurer_purchase_shares, name='treasurer_buy_shares'),
     path ('treasurer_pay_loan/<int:loan_id>/', views.treasurer_pay_loan ,name='treasurer_pay_loan'),
    path ('approve_loan/<int:loan_id>', views.approve_loan, name='approve_loan'),
     path ('download_receipt/<int:saving_id>', views.download_receipt, name='download_receipt'),
   # path ('manage_loan_requests', views.manage_loan_requests, name='manage_loan_requests'),
    path ('record_transaction', views.record_transaction, name='record_transaction'),
    path ('initiate_stk_push', views.initiate_stk_push, name='initiate_stk_push'),
    path ('treasurer_dashboard',views.treasurer_dashboard,name='treasurer_dashboard'),
    path('monthly_repayment_report',views.monthly_repayment_report, name='monthly_repayment_report'),
    path ('all_savings', views.all_savings, name='all_savings'),
    path('my_savings', views.my_savings, name='my_savings'),
    path('my_loans', views.my_loans, name='my_loans'),
    path('member_individual_report', views.member_individual_report, name='member_individual_report'),
    path('my_shares', views.my_shares, name='my_shares'),
    path('loans/pending/', views.pending_loans_view, name='pending_loans'),
    path('loans/approved/', views.approved_loans_view, name='approved_loans'),
    path('loans/rejected/', views.rejected_loans_view, name='rejected_loans'),
    path('loans/Completed/', views.Completed_loans, name='Completed_loans'),
     path('loans/active_loan/', views.active_loan, name='active_loan'),
    path('reject_loan/<int:loan_id>', views.reject_loan, name='reject_loan'),
    path('disburse_loan/<int:loan_id>', views.disburse_loan, name='disburse_loan'),
    path('calculate_loan_risk', views.calculate_loan_risk, name='calculate_loan_risk'),
    path('calculate_penalty',views.calculate_penalty, name='calculate_penalty'),
    path ('Members', views.Members, name='Member'),
        
    # urls.py
path('respond_guarantor/<int:guarantor_id>/<str:action>/', views.respond_guarantor, name='respond_guarantor'),
path('loan_detail/<int:loan_id>/', views.loan_detail, name='loan_detail'),
path ('mpesa_callback/', views.mpesa_callback, name='mpesa_callback'),
]
