# Generated by Django 5.2.11 on 2026-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(choices=[('normal Loan', 'Normal Loan'), ('choll fees', 'Scholl fees'), ('emergency', 'Emergency'), ('personal', 'Personal')], default='normal Loan', max_length=50),
        ),
    ]
