# Generated by Django 5.2.11 on 2026-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='True if migrated from paper records'),
        ),
        migrations.AddField(
            model_name='loan',
            name='legacy_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Balance brought forward from paper', max_digits=12),
        ),
        migrations.AddField(
            model_name='xmasloan',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='True if this loan was migrated from paper records.'),
        ),
        migrations.AddField(
            model_name='xmasloan',
            name='manual_interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override interest for paper records.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurpose',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
