# Generated by Django 5.2.11 on 2026-04-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='Gross_salary',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='net_salary',
        ),
    ]
