# Generated by Django 5.2.11 on 2026-04-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_loan_is_legacy_loan_legacy_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(choices=[('normal', 'Normal Loan'), ('school_fees', 'School Fees'), ('emergency', 'Emergency'), ('personal', 'Personal')], default='normal Loan', max_length=50),
        ),
    ]
