# Generated by Django 5.2.11 on 2026-04-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_loan_gross_salary_remove_loan_net_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_topup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='replaces_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.loan'),
        ),
    ]
