# Generated by Django 5.2.11 on 2026-04-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_gross_salary_profile_net_salary'),
        ('home', '0003_loan_is_topup_loan_replaces_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmasLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('repayment_period', models.IntegerField(default=3)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disbursed', 'Disbursed'), ('cleared', 'Cleared')], default='pending', max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xmas_loans', to='Users.profile')),
            ],
            options={
                'unique_together': {('member', 'year')},
            },
        ),
    ]
