# Generated by Django 5.2.11 on 2026-04-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
