# Generated by Django 5.2.11 on 2026-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_xmasloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmasloan',
            name='chairman_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xmasloan',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xmasloan',
            name='secretary_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xmasloan',
            name='treasurer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='xmasloan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('cleared', 'Cleared')], default='pending', max_length=20),
        ),
    ]
