# Generated by Django 5.2.11 on 2026-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_loan_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='Othes_Guarantor',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
