# Generated by Django 5.2.11 on 2026-03-14 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_loan_othes_guarantor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration_months',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)]),
        ),
    ]
