# Generated by Django 5.2.11 on 2026-04-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_xmasloan_chairman_approved_xmasloan_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmasloan',
            old_name='chairman_approved',
            new_name='admin_approved',
        ),
        migrations.RenameField(
            model_name='xmasloan',
            old_name='secretary_approved',
            new_name='staff_approved',
        ),
        migrations.RemoveField(
            model_name='xmasloan',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='xmasloan',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xmasloan',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xmasloan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('disbursed', 'Disbursed'), ('cleared', 'Cleared')], default='pending', max_length=20),
        ),
    ]
