# Generated by Django 5.2.11 on 2026-04-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_xmasloanrepaymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='is_xmas',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='XmasLoanRepaymentSchedule',
        ),
    ]
