# Generated by Django 5.2.11 on 2026-03-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycontribution',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
