# Generated by Django 5.2.11 on 2026-04-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_loanrepayment_is_xmas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved')], default='pending', max_length=20),
        ),
    ]
