# Generated by Django 5.2.11 on 2026-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_xmasloan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='is_xmas',
            field=models.BooleanField(default=True),
        ),
    ]
