# Generated by Django 5.2.11 on 2026-04-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_loanrepaymentschedule_is_xmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmasloan',
            name='is_disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
