# Generated by Django 5.2.11 on 2026-04-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_xmasloan_is_disbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmasloan',
            name='installments',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='xmasloan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=25.9, max_digits=5),
        ),
    ]
