# Generated by Django 5.2.11 on 2026-04-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_xmasloan_installments_alter_xmasloan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.loan'),
        ),
    ]
