# Generated by Django 5.2.11 on 2026-04-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_loanrepayment_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepaymentschedule',
            name='is_xmas',
            field=models.BooleanField(default=False),
        ),
    ]
