# Generated by Django 5.2.11 on 2026-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_loanrepaymentschedule_is_xmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmasloan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('partially_approved', 'Partially Approved'), ('cleared', 'Cleared'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
