# Generated by Django 5.2.11 on 2026-04-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_xmasloan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='xmas_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='home.xmasloan'),
        ),
    ]
