# Generated by Django 5.2.11 on 2026-04-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_loanrepaymentschedule_xmas_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepaymentschedule',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.loan'),
        ),
    ]
