# Generated by Django 5.2.11 on 2026-04-14 07:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_phone_number'),
        ('home', '0018_alter_loanrepaymentschedule_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='Othes_Guarantor',
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='insurance',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.90'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(choices=[('normal Loan', 'Normal Loan'), ('school fees', 'School fees'), ('emergency', 'Emergency'), ('personal', 'Personal')], default='normal Loan', max_length=50),
        ),
        migrations.CreateModel(
            name='HRNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
