# Generated by Django 5.2.11 on 2026-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_loan_othes_guarantor_alter_loan_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='xmasloan',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending_guarantors', 'Pending Guarantors'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('partially_approved', 'Partially Approved'), ('disbursed', 'Disbursed'), ('defaulted', 'Defaulted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='xmasloan',
            name='installments',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='xmasloan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=9.1, max_digits=5),
        ),
        migrations.RemoveField(
            model_name='xmasloan',
            name='year',
        ),
    ]
