# Generated by Django 5.2.11 on 2026-04-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_xmasrefund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmasrefund',
            old_name='created_at',
            new_name='date_applied',
        ),
        migrations.AddField(
            model_name='xmasrefund',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xmasrefund',
            name='date_disbursed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xmasrefund',
            name='staff_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xmasrefund',
            name='treasurer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='xmasrefund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('partially_approved', 'Partially Approved'), ('cleared', 'Cleared'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='xmasrefund',
            name='year',
            field=models.IntegerField(),
        ),
    ]
