# Generated by Django 5.2.11 on 2026-04-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_profile_month'),
        ('home', '0022_rename_created_at_xmasrefund_date_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalShareRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.IntegerField(default=2026)),
                ('reason', models.CharField(choices=[('exit', 'Exit from SACCO'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=50)),
                ('processing_fee_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_approved', 'Partially Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=30)),
                ('staff_approved', models.BooleanField(default=False)),
                ('treasurer_approved', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
        ),
    ]
