# Generated by Django 5.2.11 on 2026-04-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_capitalsharerefund_processing_fee_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
