# Generated by Django 5.2.11 on 2026-04-16 18:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_profile_membership_number'),
        ('home', '0025_loanrepaymentschedule_date_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('bank_charge', 'Bank Charges'), ('committee_allowance', 'Committee Allowances'), ('airtime', 'Airtime'), ('cleaning', 'Cleaning Expenses'), ('pr', 'Public Relations'), ('audit_fees', 'Audit Fees'), ('transport', 'Transport'), ('stationery', 'Printing and Stationery'), ('refreshment', 'Refreshment'), ('repairs', 'Office Repairs'), ('other', 'Other Expenses')], max_length=50)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_spent', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Petty Cash'), ('bank', 'Bank Transfer/Cheque'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed reason for the expense')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.profile')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date_spent'],
            },
        ),
    ]
