# """
# Django settings for SACCO project.

# Generated by 'django-admin startproject' using Django 5.2.11.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path

# import dj_database_url
# import os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-9$3yvfi(_9i(bn&24njr8*h8v0fi=mt3f4i3p%s@^@$2jhbcue'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# ALLOWED_HOSTS = ['*']


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'Users',
#     'home',
#     'crispy_forms',
#     'crispy_bootstrap5',
#     "django_bootstrap5",
#     'mathfilters',
  
# ]
# LOGIN_URL = 'Login'
# LOGIN_REDIRECT_URL = 'member_dashboard'  # fallback# settings.py
# MPESA_CONSUMER_KEY = 'zGwNsbORIOzKwqA2P3sgr0ArDopPQotM1iyyRhjGmdGj7n4T'
# MPESA_CONSUMER_SECRET = 'EMjOYhpEjagIsSvwa5Yucq68e7hGL9yAvWRvZqqLJQ9uS1E5a0ufLD73vkV8ALtg'
# MPESA_SHORTCODE = '174379'
# MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',  # Must be right after SecurityMiddleware
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
# # MIDDLEWARE = [
# #     'django.middleware.security.SecurityMiddleware',
# #     'django.contrib.sessions.middleware.SessionMiddleware',
# #     'django.middleware.common.CommonMiddleware',
# #     'django.middleware.csrf.CsrfViewMiddleware',
# #     'django.contrib.auth.middleware.AuthenticationMiddleware',
# #     'django.contrib.messages.middleware.MessageMiddleware',
# #     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# #     'django.middleware.security.SecurityMiddleware',
# #     'whitenoise.middleware.WhiteNoiseMiddleware',
# # ]

# ROOT_URLCONF = 'SACCO.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'SACCO.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }
# DATABASES = {
#     'default': dj_database_url.config(
#         default='postgresql://sacco_asbe_user:47QnEQuRbzyHoFVT7GphT0GTLdwymsc3@dpg-d7auiscvjg8s73eo1h6g-a.oregon-postgres.render.com/sacco_asbe',
#         conn_max_age=600,
#         ssl_require=True
#     )
# }

# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/
# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# AUTH_USER_MODEL = 'Users.CustomUser'
# AUTHENTICATION_BACKENDS=["Users.EmailBackend.EmailBackend",  # your custom email backend
#     'django.contrib.auth.backends.ModelBackend',  # fallback
# ]
# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = 'member_dashboard'
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# SACCO/settings.py

from pathlib import Path
import os
import dj_database_url

# --------------------------
# BASE DIR
# --------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------
# SECURITY
# --------------------------
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-9$3yvfi(_9i(bn&24njr8*h8v0fi=mt3f4i3p%s@^@$2jhbcue'
)
# DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'
DEBUG =  True # Set to False for production, can be overridden by env var
ALLOWED_HOSTS = ['*']  # or set your Render URL

# --------------------------
# APPLICATIONS
# --------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Users',
    'home',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_bootstrap5',
    'mathfilters',
]

# --------------------------
# MIDDLEWARE
# --------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # must come right after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------
# URLS & WSGI
# --------------------------
ROOT_URLCONF = 'SACCO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # optional: custom templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SACCO.wsgi.application'

# --------------------------
# DATABASE
# --------------------------
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://eldoret_user:mRntB6itarrj0Jj8ay4CRj2pEkRb4TQj@dpg-d7b9fcmdqaus73d60mj0-a.oregon-postgres.render.com/eldoret',
        conn_max_age=600,
        ssl_require=True
    )
}

# --------------------------
# AUTH
# --------------------------
AUTH_USER_MODEL = 'Users.CustomUser'
AUTHENTICATION_BACKENDS = [
    "Users.EmailBackend.EmailBackend",  # custom email backend
    "django.contrib.auth.backends.ModelBackend",  # fallback
]
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'member_dashboard'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# --------------------------
# INTERNATIONALIZATION
# --------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------
# STATIC FILES
# --------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # where collectstatic will copy files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # local development files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# --------------------------
# MEDIA FILES (optional if you have uploads)
# --------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --------------------------
# EXTERNAL SERVICES (MPESA)
# --------------------------
MPESA_CONSUMER_KEY = os.environ.get('MPESA_CONSUMER_KEY', 'zGwNsbORIOzKwqA2P3sgr0ArDopPQotM1iyyRhjGmdGj7n4T')
MPESA_CONSUMER_SECRET = os.environ.get('MPESA_CONSUMER_SECRET', 'EMjOYhpEjagIsSvwa5Yucq68e7hGL9yAvWRvZqqLJQ9uS1E5a0ufLD73vkV8ALtg')
MPESA_SHORTCODE = '174379'
MPESA_PASSKEY = os.environ.get('MPESA_PASSKEY', 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919')

# --------------------------
# DEFAULT PK
# --------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'